[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=/var/run/supervisord.pid


[program:nagios]
command=/usr/sbin/nagios /etc/nagios/nagios.cfg
autostart=true
autorestart=true
stdout_logfile=/var/log/nagios.out.log
stderr_logfile=/var/log/nagios.err.log


[program:nrpe]
command=/usr/sbin/nrpe -c /etc/nagios/nrpe.cfg -d
autostart=true
autorestart=true
stdout_logfile=/var/log/nrpe.out.log
stderr_logfile=/var/log/nrpe.err.log


[program:php-fpm]
command=/usr/sbin/php-fpm
autostart=true
autorestart=true
stdout_logfile=/var/log/php-fpm.out.log
stderr_logfile=/var/log/php-fpm.err.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
stdout_logfile_backups=5
stderr_logfile_backups=5

[program:httpd]
command=/usr/sbin/httpd -DFOREGROUND
autostart=true
autorestart=true
stdout_logfile=/var/log/httpd.out.log
stderr_logfile=/var/log/httpd.err.log
